my_app/__init__.py
from flask import Flask,redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager,current_user, logout_user

from functools import wraps

app = Flask(__name__)

app.config.from_object('configuration.DevelopmentConfig')
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)

login_manager.login_view = "fauth.login"

def rol_admin_need(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        if current_user.rol.value != "admin":
            logout_user()
            return redirect(url_for("fauth.login"))
            #login_manager.unauthorized()
            #return "Tu debes ser admin", 403            
        return f(*args, **kwds)
    return wrapper


from my_app.product.viewsProduct import product
from my_app.product.viewsCategory import category
from my_app.auth.views import auth
from my_app.fauth.views import fauth

#rest api
from my_app.rest_api import product_api
from my_app.rest_api import category_api
#importar vistas
app.register_blueprint(product)
app.register_blueprint(category)
#app.register_blueprint(auth)
app.register_blueprint(fauth)
db.create_all()

@app.template_filter('mydouble')
def mydouble_filter(n:int):
    return n*2
#postgres

my_app/fauth/views.py
from flask import Blueprint, render_template
from flask import request,flash,get_flashed_messages
from flask import abort, redirect, url_for, session
from my_app import db
from my_app.auth.model.user import RegisterForm, LoginForm, User
#from flask import abort
#from werkzeug import abort
from flask_login import login_user,logout_user,current_user,login_required
from my_app import login_manager

fauth =  Blueprint('fauth',__name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@fauth.route('/register', methods=('GET', 'POST'))
def register():
   
   ## validamos si esta logueado
   #if session.get('username'):
   if 'username' in session:
      print(session['username'])

   form = RegisterForm(meta={'csrf':False}) 
   if form.validate_on_submit():  
      c = User.query.filter_by(username = form.username.data).all()
      if c:
         flash("El usuario ya existe en el sistema","danger")               
      else:   
         p = User(form.username.data,form.password.data)
         db.session.add(p)
         db.session.commit()    
         flash("Usuario creado con exito")      
      return redirect(url_for('fauth.register'))

   if form.errors:
      flash(form.errors,"danger")     
   return render_template('auth/register.html',form = form)

@fauth.route('/login', methods=('GET', 'POST'))
def login():

   if current_user.is_authenticated:
      flash("Tu sesión esta abierta")      
      return redirect(url_for('product.index'))      

   form = LoginForm(meta={'csrf':False}) 
   if form.validate_on_submit():  
      user = User.query.filter_by(username = form.username.data).first()
      if user and user.check_password(form.password.data):
         #registramos la sesion
         login_user(user)
         flash("Bienvenido de nuevo " + user.username)
         next = request.form['next']
         print(next)
         # is_safe_url should check if the url is safe for redirects.
         # See http://flask.pocoo.org/snippets/62/ for an example.
         #if not is_safe_url(next):
         #      return flask.abort(400)       
         return redirect(next or url_for('product.index'))
      else:   
         flash("Usuario o contraseña incorrectos")      

   if form.errors:
      flash(form.errors,"danger")     
   return render_template('auth/login.html',form = form) 

@fauth.route('/logout', methods=('GET', 'POST'))
def logout():
   logout_user()
   return redirect(url_for('fauth.login'))

@fauth.route('/protegido')
@login_required
def protegido():
   return "vista protegida"

my_app/templates/category/_form.html
{{ form.csrf_token }}
<div class="form-group">
    {{ form.name.label }} {{ form.name(class="form-control") }}
</div>

my_app/templates/category/create.html
{% extends 'layout/base.html' %} {% block container %}

<form action="{{ url_for('category.create') }}" method="POST">
    {% include 'category/_form.html' %}
    <input type="submit" class="btn btn-dark" value="Enviar">
</form>


{% endblock %}

my_app/templates/category/filter.html
<h3>{{ product['name'] }}</h3>
<p>{{ product['category'] }}</p>
{% if product.price %}
    <p>{{ product['price'] }}</p>
{% else %}    
    <p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>
{% endif %}    

{{ "<h1>Hola Mundo</h1>" | safe }}
{{ "Esto es la descripcion de un producto" | truncate(10) }}
<p></p>
{{ "Esto es la descripcion de un producto" | count }}
<p>{{ "70.7" | float }}</p>
<p>{{ "70.7" | int }}</p>
<p>{{ 3.1415926535 | round(2) }}</p>
<p>{{ ["iphone", "ipad"] | join(", ")}}</p>
<p>{{ ["iphone", "ipad"] | length }}</p>

<p>{{ {'offer': False, 'price': 50.5, 'k': 45} | tojson }}</p>

<p>{{ 70 | mydouble }}</p>
<p>{{ product | iva }}</p>

my_app/templates/category/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %} 
{% block container %}
<a href="{{ url_for('category.create')}}" class="btn btn-primary mt-2 mb-2"><i class="fa fa-plus"></i>Crear</a>
<br>
<div class="list-category">
    {% for category in categories.items %}
    <div class="jumbotron pb-2 pt-3 {{ loop.cycle('odd', 'even') }}">
        <h3>
            <a href="{{ url_for('category.show', id = category.id) }}">{{ category['name'] }}</a>
        </h3>
        <a class="btn btn-success btn-sm" href="{{ url_for('category.update', id = category.id) }}"><i  class="far fa-edit" data-toggle="tooltip" data-placement="top" title="Editar" ></i></a>
        <button data-toggle="modal" data-target="#deleteModal" data-name="{{ category['name'] }}" data-id="{{ category['id'] }}" class="btn btn-danger btn-sm" href="{{ url_for('category.delete', id = category.id) }}"><i  class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Eliminar producto {{ category['name'] }} ?"></i></button>
    </div>
    {% endfor %}
</div>
{{ m_pagination(categories) }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-body">
                ¿Seguro que desea borrar el registro seleccionado?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <a href="#" id="categoryProduct" class="btn btn-danger">Borrar</a>
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = function() {
        $('#deleteModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var name = button.data('name') // Extract info from data-* attributes
            var id = button.data('id') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('.modal-title span').text(name)

            $("#categoryProduct").attr("href", "/category-delete/" + id)


        })
    }
</script>
{% endblock %}

my_app/templates/category/show.html
{% extends 'layout/base.html' %}

{% block container %}

    <h3>{{ product['name'] }}</h3>
    <p>{{ product['category'] }}</p>
    <p>{{ product['price'] }}</p>

{% endblock %}

my_app/templates/category/update.html
{% extends 'layout/base.html' %} {% block container %}
<form action="{{ url_for('category.update', id=category.id) }}" method="POST">
    {% include 'category/_form.html' %}
    <input type="submit" class="btn btn-dark" value="Actualizar">
</form>
{% endblock %}

my_app/templates/fragment/_alert.html
    {% with messages = get_flashed_messages() %}
    {% if messages %}            
            {% for message in messages %}        
                <div class="alert alert-primary fade show mt-3" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>            
                </div>
            {% endfor %}        
    {% endif %}
    {% endwith %} 

my_app/templates/fragment/_footer.html
<footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-dark" href="http://Grupomabarak.com.mx/">Grupomabarak.com.mx</a>
    </div>
    <!-- Copyright -->
  </footer>

my_app/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Flask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">                      
            {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('product.index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                CRUD
            </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('product.index') }}">Productos</a>
                        <a class="dropdown-item" href="{{ url_for('category.index') }}">Categorias</a>
                    </div>
                </li>
            {% endif %}            
        </ul>

        <ul class="navbar-nav">            
            {% if current_user.is_authenticated %}
            {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('fauth.login') }}">Login </a>
                </li>    
            {% endif %}

            {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Hola: {{ current_user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Perfil </a>
                        <a class="dropdown-item" href="{{ url_for('fauth.logout') }}">Logout </a>
                    </div>
                </li>
            {% endif %}            
        </ul>        
    </div>
</nav>

my_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'product/css/style.custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'global/css/style.custom.css') }}">
    <title>Document</title>
</head>

<body>
    <header> header de la app</header>

    {% include 'fragment/_nav.html' %}

    <div class="container">
        {% include 'fragment/_alert.html' %} 
        {% block container %} 
        {% endblock %}
    </div>

    {% include 'fragment/_footer.html' %}


    <script src="{{ url_for('static', filename = 'global/js/jquery-3.2.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'global/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'product/js/main.js') }}"></script>
    


</body> 
    {% block script %}
    {% endblock %}

</html>

my_app/templates/macro/_pagination.html
{% macro m_pagination(pagination) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.prev_num) }}">&laquo;</a></li>
        {% endif %}        
        {%- for page in pagination.iter_pages() %}
            {% if page != pagination.page %}
                <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=page) }}">{{ page }}</a></li>
            {% else %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ page }} <span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        {%- endfor %}
        {% if pagination.has_prev %}
        <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.prev_num) }}">&raquo;</a></li>
        {% endif %}        

    </ul>        
</nav>
  
{%- endmacro %}

my_app/templates/product/_form.html
{{ form.csrf_token }}
<div class="form-group">
        {{ form.name.label }} 
        {{ form.name(class="form-control") }}
</div>        
        
<div class="form-group">
        {{ form.price.label }} 
        {{ form.price(class="form-control") }}
</div>

<div class="form-group">
        {{ form.category_id.label }} 
        {{ form.category_id(class="form-control") }}
</div>

my_app/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    
    <form action = "{{ url_for('product.create') }}" method="POST">
        {% include 'product/_form.html' %}        
        <input type="submit" class="btn btn-dark" value="Enviar">
    </form>


{% endblock %}

my_app/templates/product/filter.html
<h3>{{ product['name'] }}</h3>
<p>{{ product['category'] }}</p>
{% if product.price %}
    <p>{{ product['price'] }}</p>
{% else %}    
    <p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>
{% endif %}    

{{ "<h1>Hola Mundo</h1>" | safe }}
{{ "Esto es la descripcion de un producto" | truncate(10) }}
<p></p>
{{ "Esto es la descripcion de un producto" | count }}
<p>{{ "70.7" | float }}</p>
<p>{{ "70.7" | int }}</p>
<p>{{ 3.1415926535 | round(2) }}</p>
<p>{{ ["iphone", "ipad"] | join(", ")}}</p>
<p>{{ ["iphone", "ipad"] | length }}</p>

<p>{{ {'offer': False, 'price': 50.5, 'k': 45} | tojson }}</p>

<p>{{ 70 | mydouble }}</p>
<p>{{ product | iva }}</p>

my_app/templates/product/show.html
{% extends 'layout/base.html' %}

{% block container %}

    <h3>{{ product['name'] }}</h3>
    <p>{{ product['category'] }}</p>
    <p>{{ product['price'] }}</p>

{% endblock %}